// Generated by gencpp from file assignment_2_2022/GoalCountResponse.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_2_2022_MESSAGE_GOALCOUNTRESPONSE_H
#define ASSIGNMENT_2_2022_MESSAGE_GOALCOUNTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment_2_2022
{
template <class ContainerAllocator>
struct GoalCountResponse_
{
  typedef GoalCountResponse_<ContainerAllocator> Type;

  GoalCountResponse_()
    : reached(0)
    , cancelled(0)  {
    }
  GoalCountResponse_(const ContainerAllocator& _alloc)
    : reached(0)
    , cancelled(0)  {
  (void)_alloc;
    }



   typedef uint32_t _reached_type;
  _reached_type reached;

   typedef uint32_t _cancelled_type;
  _cancelled_type cancelled;





  typedef boost::shared_ptr< ::assignment_2_2022::GoalCountResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment_2_2022::GoalCountResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GoalCountResponse_

typedef ::assignment_2_2022::GoalCountResponse_<std::allocator<void> > GoalCountResponse;

typedef boost::shared_ptr< ::assignment_2_2022::GoalCountResponse > GoalCountResponsePtr;
typedef boost::shared_ptr< ::assignment_2_2022::GoalCountResponse const> GoalCountResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment_2_2022::GoalCountResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment_2_2022::GoalCountResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment_2_2022::GoalCountResponse_<ContainerAllocator1> & lhs, const ::assignment_2_2022::GoalCountResponse_<ContainerAllocator2> & rhs)
{
  return lhs.reached == rhs.reached &&
    lhs.cancelled == rhs.cancelled;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment_2_2022::GoalCountResponse_<ContainerAllocator1> & lhs, const ::assignment_2_2022::GoalCountResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment_2_2022

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment_2_2022::GoalCountResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_2_2022::GoalCountResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_2_2022::GoalCountResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_2_2022::GoalCountResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_2_2022::GoalCountResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_2_2022::GoalCountResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment_2_2022::GoalCountResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c67511bea917dd86becf126baeb0026c";
  }

  static const char* value(const ::assignment_2_2022::GoalCountResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc67511bea917dd86ULL;
  static const uint64_t static_value2 = 0xbecf126baeb0026cULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment_2_2022::GoalCountResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment_2_2022/GoalCountResponse";
  }

  static const char* value(const ::assignment_2_2022::GoalCountResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment_2_2022::GoalCountResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 reached\n"
"uint32 cancelled\n"
"\n"
;
  }

  static const char* value(const ::assignment_2_2022::GoalCountResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment_2_2022::GoalCountResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reached);
      stream.next(m.cancelled);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoalCountResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment_2_2022::GoalCountResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment_2_2022::GoalCountResponse_<ContainerAllocator>& v)
  {
    s << indent << "reached: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.reached);
    s << indent << "cancelled: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.cancelled);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT_2_2022_MESSAGE_GOALCOUNTRESPONSE_H
