// Generated by gencpp from file assignment_2_2022/RobotState.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_2_2022_MESSAGE_ROBOTSTATE_H
#define ASSIGNMENT_2_2022_MESSAGE_ROBOTSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment_2_2022
{
template <class ContainerAllocator>
struct RobotState_
{
  typedef RobotState_<ContainerAllocator> Type;

  RobotState_()
    : x(0.0)
    , y(0.0)
    , linear_vel(0.0)
    , angular_vel(0.0)  {
    }
  RobotState_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , linear_vel(0.0)
    , angular_vel(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _linear_vel_type;
  _linear_vel_type linear_vel;

   typedef float _angular_vel_type;
  _angular_vel_type angular_vel;





  typedef boost::shared_ptr< ::assignment_2_2022::RobotState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment_2_2022::RobotState_<ContainerAllocator> const> ConstPtr;

}; // struct RobotState_

typedef ::assignment_2_2022::RobotState_<std::allocator<void> > RobotState;

typedef boost::shared_ptr< ::assignment_2_2022::RobotState > RobotStatePtr;
typedef boost::shared_ptr< ::assignment_2_2022::RobotState const> RobotStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment_2_2022::RobotState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment_2_2022::RobotState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment_2_2022::RobotState_<ContainerAllocator1> & lhs, const ::assignment_2_2022::RobotState_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.linear_vel == rhs.linear_vel &&
    lhs.angular_vel == rhs.angular_vel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment_2_2022::RobotState_<ContainerAllocator1> & lhs, const ::assignment_2_2022::RobotState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment_2_2022

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment_2_2022::RobotState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_2_2022::RobotState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_2_2022::RobotState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_2_2022::RobotState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_2_2022::RobotState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_2_2022::RobotState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment_2_2022::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e3f84c78187b4b315d1348ed62c074b8";
  }

  static const char* value(const ::assignment_2_2022::RobotState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe3f84c78187b4b31ULL;
  static const uint64_t static_value2 = 0x5d1348ed62c074b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment_2_2022::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment_2_2022/RobotState";
  }

  static const char* value(const ::assignment_2_2022::RobotState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment_2_2022::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 linear_vel\n"
"float32 angular_vel\n"
;
  }

  static const char* value(const ::assignment_2_2022::RobotState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment_2_2022::RobotState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.linear_vel);
      stream.next(m.angular_vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment_2_2022::RobotState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment_2_2022::RobotState_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "linear_vel: ";
    Printer<float>::stream(s, indent + "  ", v.linear_vel);
    s << indent << "angular_vel: ";
    Printer<float>::stream(s, indent + "  ", v.angular_vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT_2_2022_MESSAGE_ROBOTSTATE_H
